#Embed binary shader bytecode as a C++ constexpr byte array.
#
#Usage:
#cmake - P bin_to_cpp.cmake
#- DINPUTS = "a;b;c" - DSYMBOLS = "sa;sb;sc"
#- DOUTPUT = out.hpp - DNAMESPACE = jrpgmaker::shaders
#
#The generated header is a build artifact; the shader source and the committed
#bytecode are the only sources of truth(see docs / 01 - architecture.md ADR - 003).

if (NOT DEFINED INPUTS OR NOT DEFINED SYMBOLS OR NOT DEFINED OUTPUT)
message(FATAL_ERROR
        "usage: cmake -P bin_to_cpp.cmake -DINPUTS=a;b -DSYMBOLS=s1;s2 -DOUTPUT=out.hpp") endif()

    list(LENGTH INPUTS input_count) list(LENGTH SYMBOLS symbol_count) if (
        NOT input_count EQUAL
            symbol_count) message(FATAL_ERROR
                                  "INPUTS and SYMBOLS must have the same length") endif()

        file(WRITE "${OUTPUT}"
                   "// Generated by bin_to_cpp.cmake. Do not edit.\n"
                   "#pragma once\n\n"
                   "#include <cstddef>\n\n"
                   "namespace ${NAMESPACE} {\n\n")

            math(EXPR last_index
                 "${input_count} - 1") foreach (index RANGE 0 ${last_index}) list(GET INPUTS ${
                index} input_file) list(GET SYMBOLS ${index} symbol_name)

                file(READ "${input_file}" hex_data HEX) string(
                    REGEX REPLACE
                    "(..)"
                    "std::byte{0x\\1}, " hex_bytes
                    "${hex_data}") string(LENGTH "${hex_data}" hex_length) math(EXPR byte_length
                                                                                "${hex_length} / 2")

                    file(APPEND
                         "${OUTPUT}"
                         "inline constexpr std::byte ${symbol_name}[] = {\n${hex_bytes}\n};\n"
                         "inline constexpr std::size_t ${symbol_name}_size = ${byte_length};\n\n")
                        endforeach()

                            file(APPEND "${OUTPUT}"
                                        "} // namespace ${NAMESPACE}\n")
